### ISSUE TITLE
登陆流程问题

### ISSUE THREAD

**Issue by ynnyh** [pmg1989/dva-admin#14]
如果我想把本地模拟的登陆替换为与服务器交互，应该怎么操作呢，谢谢

**Comment by pmg1989** [comment]
与服务器交互的话，请将`conf/webpack.config.js`中的 `webpackConfig.plugins 'newband.admin.isMock': true`改为false，以及 `src/utils/index.js`中的`export request from './request-mock'`改为`export request from './request'`即可

**Comment by ynnyh** [comment]
那webpack.config.release.js和webpack.config.staging.js里面的API_HOST需要修改吗，这个如果跨域的话应该在哪里处理呢，麻烦您了

**Comment by pmg1989** [comment]
嗯，需要修改成你的后端API地址的，跨域的处理跟前端没关系了，后端处理就可以了

**Comment by ynnyh** [comment]
请问您登陆的时候ajax请求在哪里拦截的，应该不是在webpack中进行数据发送的吧

**Comment by ynnyh** [comment]
您好，我在登陆时向处理器发送数据，发现有跨域问题，这个在前端方面能解决吗

**Comment by pmg1989** [comment]
报什么错误，能描述的详细点么

**Comment by ynnyh** [comment]
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource 报的这个错误

**Comment by pmg1989** [comment]
这已经是后端的问题了，你服务器设置下`Access-Control-Allow-Origin`站点就可以了

**Comment by ynnyh** [comment]
请问我在models/app.js中遇到这个问题，const data = yield call(login, params)这句话只能返回success:false，这个要怎么解决呢

**Comment by pmg1989** [comment]
@ynnyh ,你查下你的ajax请求返回的数据结构，我在`utils/request.js` 的 handelData 方法中处理了返回的数据结构

**Comment by ynnyh** [comment]
您好，请问这个系统，使用了好多框架，会不会让这个系统变得过于庞大呢？

**Comment by pmg1989** [comment]
项目在webpack打包的时候，js已经分开模块化打包了，所以从js的体量上来说，已经是可以接受的了。至于框架的使用，除了一些必要的react生态圈内的框架，其他也都是按业务需求可选择性使用的，个人感觉也没必要担心因为使用框架的多少，而影响系统的性能。

**Comment by ynnyh** [comment]
请问我将你的路由里的菜单全部删除，加自己的东西，你的权限我把数字改成字符串，现在登录可以跑通，但是就是跳转不进去，这个是怎么回事呢？

**Comment by ynnyh** [comment]
你好，我想问一下，你的页面里面的增加操作是表单提交吗？为什么我看的不是表单提交，但是请求里面是表单提交呢

**Comment by pmg1989** [comment]
是AJAX put/post 表单提交，不是form表单提交

**Comment by ynnyh** [comment]
我现在的问题是因为是表单提交，后台要求content-type是application/json，所以我想改成不用表单提交的方式，应该怎么修改呢，现在会报415（不支持的媒体类型）错误码

**Comment by pmg1989** [comment]
`axios.post(url, {
    headers: {
        'Content-Type': 'application/json'
    }
})`，不可以么

**Comment by ynnyh** [comment]
请问我们老大说要做到前后端完全分离，想把跨域代理放在前端处理，然后我想在proxy.config.js中处理，请问这样子能不能解决跨域问题呢

**Comment by ynnyh** [comment]
这个项目在构建时，能不能在node.js也就是dora-js这块加一个代理将服务转发，这样子就能解决跨域问题，这个方法可行不？如果可行能不能给我个示例代码啊，谢谢

**Comment by pmg1989** [comment]
proxy.config.js应该是可以的，只是我这边也没有示例，具体你可以去[dora-plugin-proxy](https://github.com/dora-js/dora-plugin-proxy/issues)看看
