### ISSUE TITLE
Role/ModelForm TabelTree组件的耦合度有点高啊 请教下该组件的实现思路

### ISSUE THREAD

**Issue by cdscawd** [pmg1989/dva-admin#15]
望提示一下 谢谢

**Comment by cdscawd** [comment]
![wx20170707-155920](https://user-images.githubusercontent.com/16070662/27948674-42822b3c-632d-11e7-8867-0d74874a1a0c.png)

**Comment by pmg1989** [comment]
嗯，是的，这块的代码量因为也不是很多，所以也就没再细化了。主要思路是先拿到所有菜单权限数据，绑定到DataTable，再拿到当前登录用户的所有权限，填充Checkbox，其实也就可以了。

**Comment by cdscawd** [comment]
我目前在解决的问题是这个Table组件渲染的问题 感觉有点难度。。。
<img width="1443" alt="wx20170707-161751 2x" src="https://user-images.githubusercontent.com/16070662/27949356-ffa6fb82-632f-11e7-884d-98b506b3a5e1.png">

**Comment by pmg1989** [comment]
@cdscawd 解决了么？
