### ISSUE TITLE
自己搭建的站点上鼠标滑过ant-card类元素时会出现滚动条

### ISSUE THREAD

**Issue by yimelia** [pmg1989/dva-admin#16]
求助，我直接访问demo站点时查看的元素是一切正常的，但是自己clone了一份代码run dev后，访问localhost:8000，所有的ant card元素在鼠标hover的时候，会自动出现滚动条，并把别的元素挤开

![image](https://user-images.githubusercontent.com/6896468/28007802-74579d3e-6587-11e7-9605-bc1e473a31ec.png)

浏览器为Chrome最新版：59.0.3071.115
操作系统为Win7
打开文档中搭建的demo站点时没有问题

**Comment by pmg1989** [comment]
嗯，我也查了，应该是antd版本升级造成的，你查下你的antd版本，然后尝试`yarn upgrade antd@2.11.0`，回退一下吧，后期看下是否antd会修复这个问题
