### ISSUE TITLE
请教关于safari浏览器上editor中选择文本颜色和背景颜色选择不了的问题

### ISSUE THREAD

**Issue by ouyangyu** [pmg1989/dva-admin#17]
在Safari浏览器上，编辑器选择文本颜色和背景颜色选择不了，下拉时颜色选择没有出现，这是浏览器兼容问题吗？

**Comment by pmg1989** [comment]
我这边mac safari，测试了下，文本颜色是可以操作的，不知道你那边什么情况。因为本人项目中有使用到七牛，所以选用的富文本编辑器是[react-lz-editor](https://github.com/leejaen/react-lz-editor)，如果你没有这块需求，你也可以选用其他富文本编辑器的
