### ISSUE TITLE
偶尔出现未登陆先进入 dashboard ，然后再跳转至登录页面的问题？

### ISSUE THREAD

**Issue by jzoe** [pmg1989/dva-admin#19]
这个问题碰见好几次了，不知道各位有没有遇到过！

**Comment by pmg1989** [comment]
按理说是不应该出现的，在`router-dynamic.js`路由那块我已经做了onEnter拦截，如果没有拦截成功，才会在`models/app.js`中再次拦截，这时候才有可能看到dashborad内容。
