### ISSUE TITLE
想增加一个弹出窗口,该怎么改?

### ISSUE THREAD

**Issue by lijieray** [pmg1989/dva-admin#25]
![1111](https://user-images.githubusercontent.com/24906835/30847764-4899516c-a2cf-11e7-8f89-b8c67debea21.png)
弹出框会重叠,应该怎么改?

**Comment by pmg1989** [comment]
目前项目里控制弹框的显示的状态是modal.visible，如果需要新增弹出框，就在相关的业务model里自定义一个新的弹窗显示标识应该就可以了
