### ISSUE TITLE
一个页面，怎样做定时刷新？

### ISSUE THREAD

**Issue by koupeng** [pmg1989/dva-admin#27]
一个页面，怎样做定时刷新？感觉使用setTimeout或setInterval都有问题，，你有什么好的方案么？

**Comment by pmg1989** [comment]
为什么会有问题，你用在什么业务场景里的呢

**Comment by koupeng** [comment]
sorrycc的回复解决了我的问题。
可以在 effect 里写个无限循环，比如：

while (true) {
  yield fetch(data);
  yield delay(300);
}
然后，你可以需要适时地关闭或者开启他，可以在 state 里加个开关。比如：

while (true) {
  const enableFetch = yield select(state => state.namespace.enableFetch);
  if (enableFetch) {
    yield fetch(data);
  }
  yield delay(300);
}
