### ISSUE TITLE
更新之后为什么跑步起来了报错了，是不是有的第三方插件为 --save在dev中呢？

### ISSUE THREAD

**Issue by tianzhiyahaizhijiao** [pmg1989/dva-admin#28]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm WARN react-countup@2.4.0 requires a peer of react@^16.0.0 but none was insta
lled.
npm WARN slick-carousel@1.8.1 requires a peer of jquery@>=1.8.0 but none was ins
talled.
npm WARN eslint-config-airbnb@15.1.0 requires a peer of eslint-plugin-jsx-a11y@^
5.1.1 but none was installed.

**Comment by tianzhiyahaizhijiao** [comment]
12

**Comment by pmg1989** [comment]
应该不至于啊，我刚试了重新安装是没问题，你查下你的npm版本，或者用yarn安装试试呢

**Comment by tianzhiyahaizhijiao** [comment]
npm3.10.8 我试了cnpm直接报下面的错：
Failed to start the server, since you have enabled dllPlugin, but have not run `
roadhog buildDll` before `roadhog server`.

你这个项目我一直有关注，之前的版本好像没问题，我更新后，这边老报错了，不知道为什么

**Comment by pmg1989** [comment]
那应该是npm版本的问题了，你升级下你的npm吧，3.10有点老了，感谢你的关注。

**Comment by pmg1989** [comment]
那你试下运行 cnpm run build:dll 或者 cnpm run buildDll，应该就可以了，感谢你的关注。

**Comment by tianzhiyahaizhijiao** [comment]
cnpm run build:dll  这个应该是在cnpm install 之后吧？

**Comment by pmg1989** [comment]
是的，这次改版我使用了roadhog的dll插件，减少了开发时的编译耗时

**Comment by tianzhiyahaizhijiao** [comment]
主要是现在我cnpm install就有问题了，这个跟我的npm或者cnpm有问题吗？

**Comment by pmg1989** [comment]
你npm run dev 的时候，出现`Failed to start the server, since you have enabled dllPlugin, but have not run roadhog buildDll before roadhog server.`，说明你的包已经安装正确了，只要再运行npm run build:dll 就可以了。
