### ISSUE TITLE
怎么icon 都改不过来的吗？

### ISSUE THREAD

**Issue by coding4smart** [pmg1989/dva-admin#36]
utils/config.js 里面设置了：
logoSrc: ''
entry.dev.ejs 里面删除了以下：
        <link rel="icon" href="http://www.newband.com/images1/favicon.ico" type="image/x-icon">
entry.ejs 里面删除了以下：
<link rel="icon" href="http://www.newband.com/images1/favicon.ico" type="image/x-icon">

但是browser标题还是显示newband图标啊？

怎么破？

**Comment by pmg1989** [comment]
那应该是缓存了，清理一下试试

**Comment by coding4smart** [comment]
恩，好了。

还有2个问题：
1.修改密码跟注销放一个地方，感觉好点。
2.注销那里再加一个Menuitem，显示会有问题，多于一个的menuitem会被下面的div遮住。
