### ISSUE TITLE
为什么我改了axios.defaults.baseURL不生效

### ISSUE THREAD

**Issue by etsvain** [pmg1989/dva-admin#37]
改了baseURL之后，请求的还是本地的localhost？是mock的原因吗？新手没用过mock。。

**Comment by pmg1989** [comment]
你确认下你改的request文件是否正确，demo是mock数据，用的request-mock.js，加上`axios.defaults.baseURL = 'https://api.example.com'`也是生效的。

**Comment by etsvain** [comment]
我在request里面设置的axios.defaults.baseURL ='http://192.168.1.206:8084/';
然后我的项目请求url： http://localhost:8000/supplier/login.html
并不是预期的：http://192.168.1.206:8084/supplier/login.html

**Comment by pmg1989** [comment]
不好意思，回的有点晚，最近有点忙。你查下你的`src/utils/index.js`，request文件的引用在这里`export request from './request-mock'`,你改为`./request.js`应该就可以了。

**Comment by etsvain** [comment]
嗯嗯，我也是后来才发现的emmm，谢谢大佬
