### ISSUE TITLE
Eslint 在 VS Code 编辑器下失效

### ISSUE THREAD

**Issue by ryan-hung** [pmg1989/dva-admin#5]
作者你好，我把代码clone下来之后在vs code编辑器中打开后，发现所有.js文件第一行 import 或者 const 语句上都会返回一个 eslint 错误。[eslint] Parsing error: The keyword 'import' is reserved 。最终导致所有的 eslint 检查都没有效果。
我尝试更新了 dependencies 所有与 eslint 和 babel 相关的依赖，但是并没有什么卵用。 请问可以协助我解决一下吗？ 谢谢🙏

**Comment by pmg1989** [comment]
不好意思，回复的有点迟，vs code 我没有使用过，不太清楚是否是插件或者其他的原因，你可以试试Atom，还是蛮好用的
