### ISSUE TITLE
请教下路由后面的随机字符串怎么去掉的呢？

### ISSUE THREAD

**Issue by lpp288** [pmg1989/dva-admin#8]
请教下，
<Router history={history}>
      <Route path="/" component={require("./routes/App")} >
        <IndexRoute component={require("./routes/Home")}/>
        <Route path="home" component={require("./routes/Home")}/>
        <Route path="test">
          <Route path="test1" component={require("./routes/test")}/>
         
        </Route>
       
      
      </Route>
      
    </Router>
按照您的router.js ,但浏览器地址后面还是会出现随机字符串

**Comment by pmg1989** [comment]
根据你的描述，感觉你路由应该使用的hashHistory，所以才会出现随机字符串，可以参照 `src/index.js`
![image](https://cloud.githubusercontent.com/assets/13361827/26137225/72846bc2-3af3-11e7-9a2a-f5d8a8943662.png)
使用browserHistory应该就可以了

**Comment by lpp288** [comment]
可以了，谢谢大神
